### ISSUE TITLE
Discuss automated testing now that linter is working

### ISSUE THREAD

**Issue by jeremyhansonfinger** [Shopify/rorybot#10]
- [ ] Look into integration with current automated testing solution
- [ ] Look into integration with potential future automated testing solutions
- [ ] Ensure we can export analysis from automated testing, so we can see what people are messing up a lot, and then tweak the rules or docs to fix the problem.

**Comment by mcgain** [comment]
I'm also trialing code climate at the moment, we should discuss integration there too. It might be easier than integrating with policial.
